ISLAND_UPDATE = 1
MOVE_TO = 2
SPAWN = 3

ENTITY_UPDATE = 100
POSITION_UPDATE = 101
MESH_UPDATE = 102
STRING_UPDATE = 103

COMMAND_MOVE_TO = 1
COMMAND_SET_FOCUS = 1

COMMAND_GET_ACTIONS = 1
COMMAND_DO_ACTION = 1
