PING = 1
PONG = 2
MESSAGE = 3

# commands from the client
CMD_CONTEXTUAL_ENTITY = 10
CMD_CONTEXTUAL_POSITION = 11
CMD_MENU_REQ_ENTITY = 12
CMD_MENU_EXEC_ENTITY = 13
CMD_MENU_REQ_POSITION = 14
CMD_MENU_EXEC_POSITION = 15

# commands to the client (pattern deprecated.. functionality grouped together from now on)
DO_ASSIGN_CONTROL = 51

# entity defs
ENTITYDEF_UPDATE = 80

# data
ENTITY_UPDATE = 100
POSITION_UPDATE = 101
STRING_UPDATE = 102
FLOAT_UPDATE = 103
INT_UPDATE = 104
# BYTE_UPDATE = 105
# HALF_UPDATE = 106
ENTITYDEF_HASH_UPDATE = 107
PARENT_UPDATE = 108

# visibility
ENTITY_SHOW = 120
ENTITY_HIDE = 121
ENTITY_DESTROY = 122

# containers
CONTAINER_UPDATE = 130
CONTAINER_SHOW = 131
CONTAINER_HIDE = 132
CONTAINER_INDEX_MENU_REQ = 133

