
#define CATEGORY_VALID 1 << 0
#define CATEGORY_ANY 1 << 1
#define CATEGORY_COLLIDER 1 << 2
#define CATEGORY_TERRAIN 1 << 3
#define CATEGORY_REPLICATE 1 << 4
#define CATEGORY_BOUNDARY 1 << 5

#define COLLISION_ENTITY 1
#define COLLISION_BOUNDARY 2
