island:
- Island
- Interactive:
    include_position: true
- Space


raft:
- Meta:
    name: Raft
    description: Floats, most of the time.
- Sprite: sprites/raft.png
- RaftPhysics:
    Mass: 750
- CraftRecipe:
    consume:
      - log: 4

raft_sail:
- Sprite: sprites/raft_sail.png

raft_tiller:
- Sprite: sprites/raft_tiller.png
