island:
- Island
- Interactive:
    include_position: true
- Space


raft:
- Sprite: sprites/raft.png
- Boat
- RaftPhysics:
    Mass: 750


raft_sail:
- Sprite: sprites/raft_sail.png

raft_tiller:
- Sprite: sprites/raft_tiller.png
