meatbag:
  components:
  - class: MeatbagController
  - class: Sprite
    sprite: sprites/player.png
  - class: Dragger

large_stick:
  components:
  - class: Physical
  - class: Melee
    damage: 1

rock:
  components:
  - class: Physical
  - class: Sprite
    sprite: sprites/new/rock.png
  - class: Melee
    damage: 1
  - class: Hammer
    tier: 1
  - class: Containable

sharp_rock:
  components:
  - class: Physical
  - class: Melee
    damage: 2
  - class: Chopper
    tier: 1
  - class: Craftable
    ingredients:
    - rock
    tools:
    - Hammer.tier: 1
  - class: Containable

land_vehicle:
  components:
  - class: TileMap

stone_axe:
  components:
  - class: Physical
  - class: Equippable
  - class: Melee
    damage: 3
  - class: Chopper
    tier: 3
  - class: Craftable
    ingredients:
    - sharp_rock
    - large_stick
  - class: Sprite
    sprite: sprites/stone_axe.png
  - class: Containable
  - class: Interactive


tree:
  components:
  - class: Physical
  - class: Foliage
  - class: Choppable
  - class: Sprite
    sprite: sprites/new/tree_oak.png
  - class: Interactive

evergreen:
  components:
  - class: Physical
  - class: Foliage
  - class: Choppable
  - class: Sprite
    sprite: sprites/new/tree_pine.png
  - class: Interactive

log:
  components:
  - class: Physical
    volume: 200
    mass: 160
  - class: Sprite
    sprite: sprites/log.png
  - class: Draggable
  - class: Interactive
  - class: Containable

crate:
  components:
  - class: Physical
    volume: 1000
    mass: 5
  - class: Sprite
    sprite: sprites/bad_crate.png
  - class: Container
    capacity: 950
  - class: Interactive
  - class: Draggable

backpack:
  components:
  - class: Physical
  - class: Sprite
    sprite: sprites/backpack.png
  - class: Container
    capacity: 80
    expandable: true # expandable - volume of container will expand up to initial size + capacity
  - class: Interactive
  - class: Draggable
  - class: Wearable
    slot: back
    layer: outer

campfire:
  components:
  - class: Physical
  - class: Sprite
    sprite: