meatbag:
  components:
  - class: MeatbagController
  - class: Sprite
    sprite: sprites/player.png
  - class: Dragger

large_stick:
  components:
  - class: Melee
    damage: 1

rock:
  components:
  - class: Sprite
    sprite: sprites/new/rock.png
  - class: Melee
    damage: 1
  - class: Hammer
    tier: 1

sharp_rock:
  components:
  - class: Melee
    damage: 2
  - class: Chopper
    tier: 1
  - class: Craftable
    ingredients:
    - rock
    tools:
    - Hammer.tier: 1

land_vehicle:
  components:
  - class: TileMap

stone_axe:
  components:
  - class: Equippable
  - class: Melee
    damage: 3
  - class: Chopper
    tier: 3
  - class: Craftable
    ingredients:
    - sharp_rock
    - large_stick
  - class: Sprite
    sprite: sprites/stone_axe.png


tree:
  components:
  - class: Foliage
  - class: Choppable
  - class: Sprite
    sprite: sprites/new/tree_oak.png
  - class: Interactive

evergreen:
  components:
  - class: Foliage
  - class: Choppable
  - class: Sprite
    sprite: sprites/new/tree_pine.png
  - class: Interactive

log:
  components:
  - class: Sprite
    sprite: sprites/log.png
  - class: Draggable
  - class: Interactive

crate:
  components:
  - class: Sprite
    sprite: sprites/bad_crate.png
  - class: Container
    capacity: 125
  - class: Interactive
  - class: Draggable

campfire:
  components:
  - class: Sprite
    sprite: