meatbag:
  components:
  - class: CharacterController
  - class: Mesh
  - class: MeshMaterial

large_stick:
  components:
  - class: Melee
    damage: 1

rock:
  components:
  - class: Melee
    damage: 1
  - class: Hammer
    tier: 1

sharp_rock:
  components:
  - class: Melee
    damage: 2
  - class: Chopper
    tier: 1
  - class: Craftable
    ingredients:
    - rock
    tools:
    - Hammer.tier: 1

stone_axe:
  components:
  - class: Equippable
  - class: Melee
    damage: 3
  - class: Chopper
    tier: 3
  - class: Craftable
    ingredients:
    - sharp_rock
    - large_stick

tree:
  components:
  - class: Foliage
  - class: Choppable
  - class: Mesh
  - class: MeshMaterial

crate:
  components:
  - class: Container
    capacity: 125
