large_stick:
- component: Physical
- component: Melee
  damage: 1

rock_deposit:
- component: Sprite
  sprite: sprites/assets_td/rock1.png

sharp_rock:
- component: Physical
- component: Melee
  damage: 2
- component: Chopper
  tier: 1
- component: Craftable
  ingredients:
  - rock
  tools:
  - Hammer.tier: 1
- component: Containable



stone_axe:
- component: Physical
- component: Equippable
- component: Melee
  damage: 3
- component: Chopper
  tier: 3
- component: Craftable
  ingredients:
  - sharp_rock
  - large_stick
- component: Sprite
  sprite: sprites/stone_axe.png
- component: Containable
- component: Interactive

tree_stump:
- component: Sprite
  sprite: sprites/assets_td/stump1.png

campfire:
- component: Physical
- component: Sprite
  sprite:
