meatbag:
  components:
  - class: CharacterController
  - class: Mesh
    model: models/quad.json
    material:
      map: sprites/player.png
  - class: SimpleWander
    velocity: 5.0

large_stick:
  components:
  - class: Melee
    damage: 1

rock:
  components:
  - class: Melee
    damage: 1
  - class: Hammer
    tier: 1

sharp_rock:
  components:
  - class: Melee
    damage: 2
  - class: Chopper
    tier: 1
  - class: Craftable
    ingredients:
    - rock
    tools:
    - Hammer.tier: 1

stone_axe:
  components:
  - class: Equippable
  - class: Melee
    damage: 3
  - class: Chopper
    tier: 3
  - class: Craftable
    ingredients:
    - sharp_rock
    - large_stick

tree:
  components:
  - class: Foliage
  - class: Choppable
  - class: Mesh
    type: SkinnedMesh
    model: models/quad.json
    scale: 2.0
    z: 2.0
    material:
      map: sprites/blobby_tree_bush_thing.png

crate:
  components:
  - class: Container
    capacity: 125
