large_stick:
- Mass: 1
- Volume: 1
- Melee: 1

rock_deposit:
- component: Sprite
  sprite: sprites/assets_td/rock1.png

sharp_rock:
- Mass: 1
- Volume: 1
- Melee: 2
- component: Chopper
  tier: 1
- component: Craftable
  ingredients:
  - rock
  tools:
  - Hammer.tier: 1
- component: Containable

stone_axe:
- Mass
- Volume
- Equippable
- Melee: 3
- component: Chopper
  tier: 3
- component: Craftable
  ingredients:
  - sharp_rock
  - large_stick
- component: Sprite
  sprite: sprites/stone_axe.png
- Containable
- Interactive

tree_stump:
- component: Sprite
  sprite: sprites/assets_td/stump1.png

campfire:
- Mass
- Volume
- component: Sprite
  sprite:

island:
- Island
- Interactive:
    include_position: true


raft:
- Sprite: sprites/raft.png
- Boat
- TestPhysics

raft_sail:
- Sprite: sprites/raft_sail.png

raft_tiller:
- Sprite: sprites/raft_tiller.png
