large_stick:
  components:
  - class: Physics
  - class: Melee
    damage: 1

rock_deposit:
  components:
  - class: Sprite
    sprite: sprites/assets_td/rock1.png

sharp_rock:
  components:
  - class: Physics
  - class: Melee
    damage: 2
  - class: Chopper
    tier: 1
  - class: Craftable
    ingredients:
    - rock
    tools:
    - Hammer.tier: 1
  - class: Containable



stone_axe:
  components:
  - class: Physics
  - class: Equippable
  - class: Melee
    damage: 3
  - class: Chopper
    tier: 3
  - class: Craftable
    ingredients:
    - sharp_rock
    - large_stick
  - class: Sprite
    sprite: sprites/stone_axe.png
  - class: Containable
  - class: Interactive

tree_stump:
  components:
  - class: Sprite
    sprite: sprites/assets_td/stump1.png

campfire:
  components:
  - class: Physics
  - class: Sprite
    sprite:

